### ISSUE TITLE
"try to find test_actor1@civilcookies.com from the search in Mastodon" doesn't work

### ISSUE THREAD

**Issue by kschultz1986** [dariusk/express-activitypub#5]
I don't think "try to find test_actor1@{example}.com from the search in Mastodon" will work without some sort of federation between my account on instance mastodon.social my local test implementation of this express-activitypub project.

What's the simplest way to find and follow my actor 'test_actor1@{example}.com'?

**Comment by dariusk** [comment]
Sorry I missed this! It should work without federation because what Mastodon will do is send an HTTP GET request to a particular URL when you do this. I've had it work with brand new instances that didn't exist even five seconds ago. To truly debug it you could also just paste the URL of the actor into the search, that works for all types of accounts as well.

**Comment by forrestwilkins** [comment]
I'm also unable to find my account on Mastodon.
